# Permalinks
permalink:           pretty

# Setup
title:               Personal Blog
tagline:             Technically anything!
url:                 http://rselva.net
paginate:            1
baseurl:             ""
host:				 0.0.0.0
analytics_id:  		 UA-76557621-1
tracking: 			 on	
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Selva
  url:               https://twitter.com/rselva
  email:             selva.home@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/rselva

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
