# Permalinks
permalink:           pretty

# Setup
title:               Selva
tagline:             ~$ sudo rm -rf .
url:                 http://selva.net.in
paginate:            1
baseurl:             ""
host:				 0.0.0.0
analytics_id:  		 UA-76557621-1
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Selva
  url:               https://twitter.com/mdo
  email:             selva.home@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/rselvA

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
